---
controller_credential_types:
- name: Active Directory Domain Controller Credentials
  description: Credential type for Active Directory Domain Controller Credentials
  kind: cloud
  inputs:
    fields:
    - id: default_dc_cred
      type: string
      label: Default Domain Controller Credential
      secret: true
      help_text: Default credential for domain controller operations
    - id: domain_controller_join
      type: string
      label: Domain Controller Join Credential
      secret: true
      help_text: Credential used for joining a server as a domain controller
    - id: domain_join
      type: string
      label: Domain Join Credential
      secret: true
      help_text: Credential used for joining a server to the domain
    - id: temp_password
      type: string
      label: Temporary Password
      secret: true
      help_text: Temporary password used during configuration
    required:
    - domain_controller_join
    - domain_join
  injectors:
    extra_vars:
      default_dc_cred: !unsafe '{{ default_dc_cred }}'
      domain_controller_join: !unsafe '{{ domain_controller_join }}'
      domain_join: !unsafe '{{ domain_join }}'
      temp_password: !unsafe '{{ temp_password }}'
