---
controller_credentials:
- name: Active Directory Domain Controller Credentials - activedirectoryhub
  description: Credential for activedirectoryhub
  organization: Default
  credential_type: Active Directory Domain Controller Credentials
  update_secrets: true
  inputs:
    default_dc_cred: '{{ vault_default_dc_cred }}'
    domain_controller_join: '{{ vault_domain_controller_join }}'
    domain_join: '{{ vault_domain_join }}'
    temp_password: '{{ vault_temp_password }}'
