---
controller_credentials:
- name: Azure Automation Credentials - activedirectorybuild
  description: Credential for activedirectorybuild
  organization: Default
  credential_type: Azure Automation Credentials
  update_secrets: true
  inputs:
    default_dc_cred: '{{ vault_default_dc_cred }}'
    domain_controller_join: '{{ vault_domain_controller_join }}'
    domain_join: '{{ vault_domain_join }}'
    temp_password: '{{ vault_temp_password }}'
