---
memberserversql_sql_installer_source_path: C:\Admin\SQL2016_x64_ENU
memberserversql_admin_path: C:\Admin
memberserversql_api_folder_path: C:\Admin\APIRegistration
memberserversql_domain_name: contoso.local
memberserversql_sql_instance_name: SCVMMSQL
memberserversql_sql_tcp_port: 50001
memberserversql_sql_features: SQLENGINE
memberserversql_sql_collation: SQL_Latin1_General_CP1_CI_AS
memberserversql_sql_admin_group: CONTOSO\Admin-SQL-Group
memberserversql_sql_gmsa_account: CONTOSO\sql-gmsa$
memberserversql_sql_install_shared_dir: C:\Program Files\Microsoft SQL Server
memberserversql_sql_install_shared_wow_dir: C:\Program Files (x86)\Microsoft SQL Server
memberserversql_sql_instance_dir: C:\Program Files\Microsoft SQL Server
memberserversql_sql_data_dir: C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Data
memberserversql_sql_backup_dir: C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Backup
memberserversql_timezone: Pacific Standard Time
memberserversql_ps_execution_policy: RemoteSigned
memberserversql_windows_features:
  - Net-Framework-45-Core
memberserversql_firewall_rule_name: AllowSQLConnection
memberserversql_firewall_rule_display_name: Allow SQL Connection
memberserversql_firewall_rule_description: Firewall Rule to allow SQL communication
memberserversql_firewall_rule_group: DSC Configuration Rules
memberserversql_firewall_rule_profile: Domain
memberserversql_firewall_rule_direction: Inbound
memberserversql_firewall_rule_protocol: TCP
