---
controller_credentials:
- name: Azure Automation Domain Join - memberserversql
  description: Domain join credential sourced from Azure Automation Vault via Get-AutomationPSCredential
  organization: Default
  credential_type: Azure Automation Domain Join
  update_secrets: true
  inputs:
    domain_join_user: '{{ domain_join_user }}'
    domain_join_password: '{{ vault_domain_join_password }}'
