---
controller_credentials:
- name: Azure Automation Domain Join - standalonehypervisordell
  description: Domain join credential retrieved from Azure Automation credential store
    via Get-AutomationPSCredential
  organization: Default
  credential_type: Azure Automation Domain Join
  update_secrets: true
  inputs:
    domain_join_username: '{{ domain_join_username }}'
    domain_join_password: '{{ vault_domain_join_password }}'
